filebeat.autodiscover: # docker 컨테이너에서 로그 자동 수집
  providers:
    - type: docker
      hints.enabled: true                      # 컨테이너 라벨(co.elastic.logs/*)을 힌트로 사용
      hints.default_config: # 라벨 없을 때 적용할 기본 입력
        type: container                        # 도커 JSON 로그 인풋
        paths: # 컨테이너 로그 경로
          - /var/lib/docker/containers/${data.container.id}/*.log
        stream: all                            # stdout + stderr 모두 수집

processors:
  - add_docker_metadata: ~                     # 이벤트에 컨테이너 메타데이터 추가
  - decode_json_fields: # JSON 라인만 펼쳐서 필드로 변환
      when:
        regexp:
          message: '^\s*{'                     # message가 { 로 시작하는 경우에만 파싱 (JSON형식 파싱)
      fields: [ "message" ]                    # message 필드를 JSON으로 파싱
      target: ""
      overwrite_keys: true                     # 같은 키가 있으면 덮어씀
      add_error_key: true                      # 파싱 실패 시 error 필드 추가

output.elasticsearch:
  hosts: [ "http://es01:9200","http://es02:9200","http://es03:9200" ]       # 수집 로그를 Elasticsearch로 전송

setup.kibana:
  host: "kibana:5601"                          # Kibana 접속 정보

logging.to_files: false                         # Filebeat 로그를 파일로 남기지 않음
logging.metrics.enabled: false                  # Filebeat 내부 메트릭 로깅 비활성화
setup.ilm.enabled: true                         # 인덱스 수명주기(ILM) 사용
