server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eat_together
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create-drop / create / update / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret: b3b9148e-a9df-42fd-872b-e5e00b944f1c-jwt-secret-test-key
  expiration: 3600000 # 1 hour




logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"